version: '3.5'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './certs:/etc/nginx/certs'
    networks:
      mypupio: {}
  frontend:
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=mypup.io
    networks:
      mypupio: {}
networks:
  mypupio:
    name: mypupio